// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATIL781M-HAUy5U7njads5RHeRm_whQD4',
    appId: '1:329815332848:web:0b5045b54b892b77b2ef35',
    messagingSenderId: '329815332848',
    projectId: 'velga-office-app',
    authDomain: 'velga-office-app.firebaseapp.com',
    storageBucket: 'velga-office-app.firebasestorage.app',
    measurementId: 'G-7M6F1X6RDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzkYEJZCSPHK4XCYu16pGED_wOj7i6j54',
    appId: '1:329815332848:android:16d25920870c4dbfb2ef35',
    messagingSenderId: '329815332848',
    projectId: 'velga-office-app',
    storageBucket: 'velga-office-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOqtcEmPqIPCQGAspCAI2L3mwcKIrv3YM',
    appId: '1:329815332848:ios:94b341fc5d853229b2ef35',
    messagingSenderId: '329815332848',
    projectId: 'velga-office-app',
    storageBucket: 'velga-office-app.firebasestorage.app',
    iosBundleId: 'com.example.velgaApplication',
  );

}